version: '3.3'

services:
  postgres:
    image: 'postgres:14'
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=swinemovementdb
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    logging:
      driver: json-file
      options:
        max-size: 17000m
        max-file: '5'

  redis:
    image: 'redis:3.0.6'
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/var/lib/redis/data'
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 17000m
        max-file: '5'

  kafka_zookeeper:
    image: 'bitnami/zookeeper:3'
    restart: always
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:2'
    restart: always
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - 'KAFKA_CFG_ZOOKEEPER_CONNECT=kafka_zookeeper:2181'
      - ALLOW_PLAINTEXT_LISTENER=yes
      - 'KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092'
    depends_on:
      - kafka_zookeeper

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
