version: '3.3'

services:
  postgres:
    image: 'postgres:14'
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=swinemovementdb
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    logging:
      driver: json-file
      options:
        max-size: 17000m
        max-file: '5'

  redis:
    image: 'redis:3.0.6'
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/var/lib/redis/data'
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 17000m
        max-file: '5'

  web:
    image: 'swinemovementms:1.0.0'
    command: python3 manage.py runserver 0.0.0.0:9113
    ports:
      - "9113:9113"
    environment:
      FLAVOUR: prod
    depends_on:
      - postgres

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local