# Generated by Django 4.1 on 2022-08-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swinemovement', '0002_alter_company_name_alter_movement_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premise',
            old_name='premise_id',
            new_name='id',
        ),
    ]
